### ISSUE TITLE
Python issue and can't connect with Qgis

### ISSUE THREAD

**Issue by manuelineco** [sentinel-hub/sentinelhub-qgis-plugin#14]
Hi, I have problems with SentinelHub in Qgis 3.18. Today I can´t log in, when I try it, Phyton error is shown and the console have this message:

"requests.exceptions.SSLError: HTTPSConnectionPool(host='services.sentinel-hub.com', port=443): Max retries exceeded with url: /oauth/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)')))"

I try with another computer and another version of Qgis and they have the same problem.

Thank you a lot.

Bye

**Comment by AleksMat** [comment]
Hi @manuelineco,

This is actually not an issue of our plugin but an issue of an expired SSL certificate in the Python environment that your QGIS is using. There are many threads on StackOverflow about this, such as [this one](https://stackoverflow.com/questions/51390968/python-ssl-certificate-verify-error) and [this one](https://stackoverflow.com/questions/51925384/unable-to-get-local-issuer-certificate-when-using-requests-in-python), and different solutions seem to work for different users.

**Comment by manuelineco** [comment]
Hi!

Thank you a lot, I will try it¡

Bye
