### ISSUE TITLE
Create WMS Layer from source dataspace.copernicus.eu failed

### ISSUE THREAD

**Issue by lemrm** [sentinel-hub/sentinelhub-qgis-plugin#34]
Connection is established, but I couldn't create not the WMS nor WMTS layer I selected before.

<img width="825" alt="Bildschirmfoto 2023-08-29 um 09 11 51" src="https://github.com/sentinel-hub/sentinelhub-qgis-plugin/assets/19464841/8c58b554-0569-476f-b209-621e46f58790">

**Comment by Adrok24** [comment]
Hi @lemrm  is this issue still happening?

**Comment by Adrok24** [comment]
Are you using MacOs?

**Comment by gilles-morain** [comment]
I cannot tell for @lemrm but I have the same issue and I am using macOS

**Comment by gilles-morain** [comment]
Answering to myself: QGIS comes with its own OpenSSL version.

```/Applications/QGIS.app/Contents/MacOS/bin/python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.1.1h  22 Sep 2020
/opt/homebrew/bin/python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 3.1.2 1 Aug 2023```

**Comment by gilles-morain** [comment]
NB: same computer, same configuration: it works perfectly well with the services.sentinel-hub.com endpoint, so it is really a TLS negotiation issue between QGIS and the Copernicus Dataspace endpoint

**Comment by Adrok24** [comment]
Hi, yes you are right @gilles-morain we have an issue with TLS negotiation that happens only in Apple and when using copernicus endpoint. We will inform when this is solved.

**Comment by simenojensen** [comment]
Any update on this? I have the same issue on macOS

**Comment by Adrok24** [comment]
Hi @gilles-morain  @simenojensen could you try now?

**Comment by simenojensen** [comment]
@Adrok24  Seems to work now, thank you!

**Comment by gilles-morain** [comment]
> Hi @gilles-morain @simenojensen could you try now?

Works on my end too, thanks! No update in the plugin, I guess this was solved on the server side?

**Comment by Adrok24** [comment]
Yes, it is an issue on the server side.
