### ISSUE TITLE
Landsat WMS doesn't load in QGIS SentinelHub Plugin because it comes from services-uswest2

### ISSUE THREAD

**Issue by elawrey** [sentinel-hub/sentinelhub-qgis-plugin#35]
When a configuration is setup in Sentinel Hub the Service endpoint is assigned to services.sentinel-hub.com or services-uswest2.sentinel-hub.com. If the endpoint is uswest then it doesn't work in the QGIS SentinelHub Plugin. This includes Landsat 4-5 and Landsat 8-9. This is a regression.

In Sentinel Hub Configuration Utility if a WMS configuration instance gets a Service endpoint of uswest2  (https://services-uswest2.sentinel-hub.com/ogc/wms/xxxxxx) instead of https://services.sentinel-hub.com/ogc/wms/xxxx then the uswest service doesn't work in the QGIS Sentinel Hub Plugin. 

### To reproduce:
I don't know what determines which service domain a configuration gets, however basing a configuration on the Landsat 4-5 TM Level-1 Template seems to reliably force it to uswest leading to the problem.

In https://apps.sentinel-hub.com/dashboard/#/configurations/new
1. Create a New configuration. 
Configuration name: Landsat 4-5 test (name doesn't matter)
Create configuration based on: Landsat 4-5 TM Level-1 Template
2. Check the Service endpoints / WMS it is services-uswest2
https://services-uswest2.sentinel-hub.com/ogc/wms/xxxxxx
In QGIS (3.28) install SentinelHub plugin (using 2.0.1)
3. Click on the SentinelHub plugin button. Login using OAuth client ID and client secret setup in Sentinel Hub / User Settings / OAuth clients
4. In QGIS enable the View / Panels / Debugging/Development tools so we can see the traffic. Turn on record.
5. Zoom to a location where the imagery should be viewable. With Projection EPSG:3857, Coordinate: 16242950,-1941928, Scale: 1:466923. Centered on city of Cairns, Queensland, Australia. For this I used a base map to position the map to a location that I knew the imagery should be visible for the date specified, based on its visibility in EO Browser. 
6.  In the SentinelHub plugin v2.0.1 / Create tab choose:
Configuration: Landsat 4-5 test (the one we made before)
Service type: WMS
Layer: False Color (this shouldn't matter)
CRS: EPSG: 3857 (matching QGIS project)
Time range: 2011-11-11 
Use exact date: checked
7. Click Create button.
8. Review the Debugging/Development Tools
![QGIS-SentinelHub-Plugin-not-working](https://github.com/sentinel-hub/sentinelhub-qgis-plugin/assets/20452751/252107de-0316-42f4-87ca-04f2e4315af7)

This generates an error:
Error: Error transferring https://services.sentinel-hub.com/ogc/wms/ef75ceb6-1cb7-423d-a980-a3400e468448?showLogo=false&time=2011-11-11/2011-11-11/P1D&priority=leastCC&maxcc=100&preview=1&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=16192573.51947131194,-1941989.693874951452,16291534.55562257953,-1865209.579619657248&CRS=EPSG:3857&WIDTH=696&HEIGHT=540&LAYERS=FALSE-COLOR&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE - server replied: Bad Request

This error occurs because the actual service is at https://services-uswest2.sentinel-hub.com not https://services.sentinel-hub.com. Unfortunately the user has no way of fixing this.

Landsat 8-9 layers also seem to default to uswest2 and so is also likely not to work in the QGIS SentinelHub Plugin.

**Comment by Adrok24** [comment]
Hi @elawrey, thank you for pointing out this issue. We are working on a solution for this.

**Comment by elawrey** [comment]
Thank you for the prompt response and the work around. I tried it and it worked.

**Comment by Adrok24** [comment]
The issue is solved in the new version of the plugin which is updated in the Qgis Plugin Manager.
